# Generated by Django 5.1.3 on 2024-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
