# Generated by Django 5.1.4 on 2025-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_evaluacionfisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
