# Generated by Django 5.1.4 on 2025-01-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reserva'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
