# Generated by Django 5.1.4 on 2025-01-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_reserva_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.CharField(default='1 hora', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Desocupado', 'Desocupado')], default='Ocupado', max_length=20),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table=None,
        ),
    ]
