# Generated by Django 5.1.4 on 2025-01-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_email_verified_user_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion', models.DurationField()),
                ('capacidad', models.IntegerField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.entrenador')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clase')),
            ],
            options={
                'db_table': 'asignacion',
            },
        ),
    ]
